#define PJ_CONFIG_IPHONE 1
#define PJMEDIA_SDP_NEG_ANSWER_SYMMETRIC_PT 1
#define PJSIP_AUTH_HEADER_CACHING 1
#define PJSIP_AUTH_AUTO_SEND_NEXT 1
#define PJMEDIA_HAS_OPUS_CODEC 1
#include <pj/config_site_sample.h>
